### ISSUE TITLE
Unable to generate secure boot ISO with custom kernel args

### ISSUE THREAD

**Issue by TimJones** [siderolabs/image-factory#104]
Generating a secureboot ISO works fine with the default schematic, but when I add custom kernel args (e.g. `talos.experiment.wipe=system`) the secureboot ISO fails to generate.

schematic ID: `9acd4f2454d4969f5351e85d824eb5d27f8124b56d281d8a03c924fa1a7cfd2f`

```yaml
customization:
  extraKernelArgs:
    - talos.experimental.wipe=system
```

The standard ISO download works, but the secureboot ISO download fails.
