### ISSUE TITLE
[feat] Add an endpoint to generate patch from schematic

### ISSUE THREAD

**Issue by TMaYaD** [siderolabs/image-factory#150]
Currently this can be done on the client machine using a script to post the schematic to get an id and then using sed to  generate

```yaml
machine:
  install:
    image: factory.talos.dev/installer/<id>:v1.7.6
```

It works but not elegant.

Having an end point that returns the patch directly would simplify the ops to

```sh
curl -X POST --data-binary @schematics.yaml https://factory.talos.dev/schematics-patch -o installer.patch.yaml

talosctl gen config \
  --with-secrets secrets.yaml \
  --config-patch @installer.patch.yaml \
  --config-patch @my-other-patches.patch.yaml \
  talos https://10.10.10.6:6443
```
