### ISSUE TITLE
Bug: i915 System Extension Should Not Be Available for ARM64 Architecture

### ISSUE THREAD

**Issue by philipptolksdorf** [siderolabs/image-factory#240]
The siderolabs/i915 system extension is currently selectable in the image factory when choosing ARM64 machine architecture, despite containing x86-specific code that cannot function on ARM64 systems.

# Environment
Architecture: ARM64
Version: Talos v1.10.3
Hardware: Ampere Altra Q80-30 based server
Graphics Card: Intel Arc A380
Schematic ID: [064d2c892ac9a3a7da7fa550dbdd1516908bd9dfe355ad345ff4e9d8f8b34930](https://factory.talos.dev/?arch=arm64&board=undefined&cmdline-set=true&extensions=-&extensions=siderolabs%2Fi915&extensions=siderolabs%2Fmei&platform=metal&secureboot=true&target=metal&version=1.10.3)

# Logs:

### Extension Status
```bash
talosctl -n worker-1 -e 10.10.10.4 get extensions
NODE       NAMESPACE   TYPE              ID   VERSION   NAME        VERSION
worker-1   runtime     ExtensionStatus   0    1         i915        20250509-v1.10.3
worker-1   runtime     ExtensionStatus   1    1         mei         v1.10.3
worker-1   runtime     ExtensionStatus   2    1         schematic   064d2c892ac9a3a7da7fa550dbdd1516908bd9dfe355ad345ff4e9d8f8b34930
```

### Hardware Detection
```yaml
# talosctl -n worker-1 -e 10.10.10.4 get pcidevices 0004:03:00.0 -o yaml
node: worker-1
metadata:
    namespace: hardware
    type: PCIDevices.hardware.talos.dev
    id: 0004:03:00.0
    version: 1
    owner: hardware.PCIDevicesController
    phase: running
    created: 2025-05-30T13:26:38Z
    updated: 2025-05-30T13:26:38Z
spec:
    class: Display controller
    subclass: VGA compatible controller
    vendor: Intel Corporation
    product: DG2 [Arc A380]
    class_id: "0x03"
    subclass_id: "0x00"
    vendor_id: "0x8086"
    product_id: "0x56a5"
```

```bash
# talosctl -n worker-1 -e 10.10.10.4 list /dev/dri/
NODE   NAME
1 error occurred:
 rpc error: code = Unknown desc = lstat /dev/dri: no such file or directory
```

### Intel Driver Status
```bash
# talosctl -n worker-1 -e 10.10.10.4 dmesg | grep -i intel
worker-1: kern:    info: [2025-06-02T08:29:10.658125647Z]: e100: Intel(R) PRO/100 Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.662837647Z]: e100: Copyright(c) 1999-2006 Intel Corporation
worker-1: kern:    info: [2025-06-02T08:29:10.668328647Z]: e1000: Intel(R) PRO/1000 Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.673196647Z]: e1000: Copyright (c) 1999-2006 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:10.678944647Z]: e1000e: Intel(R) PRO/1000 Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.683897647Z]: e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:10.683917647Z]: igb: Intel(R) Gigabit Ethernet Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.700849647Z]: igb: Copyright (c) 2007-2014 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:10.762010647Z]: igb 0002:04:00.0: Intel(R) Gigabit Ethernet Network Connection
worker-1: kern:    info: [2025-06-02T08:29:10.788815647Z]: Intel(R) 2.5G Ethernet Linux Driver
worker-1: kern:    info: [2025-06-02T08:29:10.793345647Z]: Copyright(c) 2018 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:10.797970647Z]: igbvf: Intel(R) Gigabit Virtual Function Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.804227647Z]: igbvf: Copyright (c) 2009 - 2012 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:10.810149647Z]: ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver
worker-1: kern:    info: [2025-06-02T08:29:10.816231647Z]: ixgbe: Copyright (c) 1999-2016 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:11.912933647Z]: ixgbe 0003:03:00.0: Intel(R) 10 Gigabit Network Connection
worker-1: kern:    info: [2025-06-02T08:29:13.000573647Z]: ixgbe 0003:03:00.1: Intel(R) 10 Gigabit Network Connection
worker-1: kern:    info: [2025-06-02T08:29:13.007225647Z]: ixgbevf: Intel(R) 10 Gigabit PCI Express Virtual Function Network Driver
worker-1: kern:    info: [2025-06-02T08:29:13.014968647Z]: ixgbevf: Copyright (c) 2009 - 2018 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:13.021128647Z]: i40e: Intel(R) Ethernet Connection XL710 Network Driver
worker-1: kern:    info: [2025-06-02T08:29:13.027387647Z]: i40e: Copyright (c) 2013 - 2019 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:13.033253647Z]: iavf: Intel(R) Ethernet Adaptive Virtual Function Network Driver
worker-1: kern:    info: [2025-06-02T08:29:13.040291647Z]: Copyright (c) 2013 - 2018 Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:13.045602647Z]: ice: Intel(R) Ethernet Connection E800 Series Linux Driver
worker-1: kern:    info: [2025-06-02T08:29:13.052119647Z]: ice: Copyright (c) 2018, Intel Corporation.
worker-1: kern:    info: [2025-06-02T08:29:13.061184647Z]: QLogic 1/10 GbE Converged/Intelligent Ethernet Driver v5.3.66
```

# Proposed Solution
Consider adding support for the Intel Xe kernel driver, which is the successor.
I would appreciate the ability to compile the Kernel with them using the Image Factory or to have a System Extension for it.
