### ISSUE TITLE
v0.7.2 version of the factory image fails with `panic: refresh interval must be greater than zero`

### ISSUE THREAD

**Issue by ajgon** [siderolabs/image-factory#244]
## Error output

```
{"level":"info","ts":1749111735.1744394,"caller":"cmd/service.go:48","msg":"starting","name":"image-factory","version":"v0.7.2","sha":"29b022e2"}
{"level":"info","ts":1749111735.7736573,"caller":"runtime/panic.go:792","msg":"shutting down","name":"image-factory"}
panic: refresh interval must be greater than zero

goroutine 1 [running]:
github.com/siderolabs/image-factory/internal/remotewrap/internal/refresher.New[...](...)
        /src/internal/remotewrap/internal/refresher/refresher.go:30
github.com/siderolabs/image-factory/internal/remotewrap.NewPuller(...)
        /src/internal/remotewrap/remotewrap.go:116
github.com/siderolabs/image-factory/internal/artifacts.NewManager(0xc000416000, {{0x2d1fe6a, 0x7}, 0x0, {0x1, 0x2, 0x0, {0x0, 0x0, 0x0}, ...}, ...})
        /src/internal/artifacts/manager.go:75 +0x855
github.com/siderolabs/image-factory/cmd/image-factory/cmd.buildArtifactsManager({_, _}, _, {{0x2d1ca0e, 0x5}, {0x2d1ca13, 0x5}, {0x2d1fe6a, 0x7}, 0x0, ...})
        /src/cmd/image-factory/cmd/service.go:257 +0x9c5
github.com/siderolabs/image-factory/cmd/image-factory/cmd.RunFactory({_, _}, _, {{0x2d1ca0e, 0x5}, {0x2d1ca13, 0x5}, {0x2d1fe6a, 0x7}, 0x0, ...})
        /src/cmd/image-factory/cmd/service.go:59 +0x490
main.runWithContext({0x322c020, 0xc0005cac80})
        /src/cmd/image-factory/main.go:56 +0xf0
main.run()
        /src/cmd/image-factory/main.go:45 +0xda
main.main()
        /src/cmd/image-factory/main.go:22 +0x13
```

## Configuration

I'm running factory with following docker compose:

```yaml
services:
  talos-factory:
    image: ghcr.io/siderolabs/image-factory:v0.7.2@sha256:6c944811d2162678e3532f810c96ab54e1e37bd9d57a5d74235b837e10cf1080
    container_name: talos-factory
    restart: unless-stopped
    user: 1000:1000
    env_file:
      - compose.env
    command:
      - "-external-url"
      - "https://factory.${ROOT_DOMAIN}"
      - "-cache-signing-key-path"
      - "/config/cache-signing-key.key"
      - "-secureboot"
      - "-secureboot-pcr-key-path"
      - "/config/pcr-signing-key.pem"
      - "-secureboot-signing-cert-path"
      - "/config/uki-signing-cert.pem"
      - "-secureboot-signing-key-path"
      - "/config/uki-signing-key.pem"
      - "-insecure-schematic-service-repository"
      - "-schematic-service-repository"
      - "${TALOS_FACTORY_INTERNAL_REGISTRY_HOST}/talos/schematic"
      - "-insecure-installer-internal-repository"
      - "-installer-internal-repository"
      - "${TALOS_FACTORY_INTERNAL_REGISTRY_HOST}/talos/images"
      - "-installer-external-repository"
      - "factory.${ROOT_DOMAIN}/talos/images"
      - "-insecure-cache-repository"
      - "-cache-repository"
      - "${TALOS_FACTORY_INTERNAL_REGISTRY_HOST}/talos/cache"
    volumes:
      - "/volumes/talos-factory/config:/config:ro"
    tmpfs:
      - /tmp:mode=755,uid=1000,gid=1000
    networks:
      - caddy
    labels:
      caddy: "*.${ROOT_DOMAIN}"
      caddy.1_@factory: "host factory.${ROOT_DOMAIN}"
      caddy.1_handle: "@factory"
      caddy.1_handle.reverse_proxy: "{{upstreams 8080}}"
    # security
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true

networks:
  caddy:
    external: true
```

`compose.env` file only contains `HOME=/tmp` so factory won't fail when ran on read-only container. 

For testing I also disabled this part:
```yaml
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true
```
and changed `/config` volume to be `rw`. Still no luck though. 

Any help will be much appreciated, thank you!
