### ISSUE TITLE
`qlogic-firmware` is not available

### ISSUE THREAD

**Issue by kvaps** [siderolabs/image-factory#86]
just tried to use:
```
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/amdgpu-firmware
            - siderolabs/bnx2-bnx2x
            - siderolabs/qlogic-firmware
            - siderolabs/drbd
            - siderolabs/zfs
            - siderolabs/i915-ucode
            - siderolabs/intel-ice-firmware
            - siderolabs/intel-ucode
            - siderolabs/amd-ucode
```

got the [error](https://factory.talos.dev/image/1a28a2edf458dc3b1f1717c80b1b2d36262848491ef210661c8c76a007686998/v1.6.4/metal-amd64.iso)
```
error enhancing profile from schematic: official extension "siderolabs/qlogic-firmware" is not available for Talos version v1.6.4
```
